# Generated by Django 4.1.7 on 2023-04-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palpites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='time',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
