# Generated by Django 4.1.7 on 2023-04-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palpites', '0002_alter_partida_id_alter_time_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='dia',
            field=models.DateTimeField(),
        ),
    ]
