# Generated by Django 4.1.7 on 2023-04-18 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palpites', '0004_alter_partida_vencedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palpite_partida',
            name='golsMandante',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='palpite_partida',
            name='golsVisitante',
            field=models.IntegerField(),
        ),
    ]
