# Generated by Django 4.1.7 on 2023-04-27 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palpites', '0005_alter_palpite_partida_golsmandante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='ano',
        ),
        migrations.AlterField(
            model_name='partida',
            name='golsMandante',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='partida',
            name='golsVisitante',
            field=models.IntegerField(default=-1),
        ),
    ]
