# Generated by Django 4.1.7 on 2023-05-20 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('palpites', '0006_remove_partida_ano_alter_partida_golsmandante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='palpites.time'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
