# Generated by Django 4.1.7 on 2023-05-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palpites', '0007_user_favorite_team_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='caminho/para/imagem_inexistente.jpg', upload_to='profile_images'),
        ),
    ]
