# Generated by Django 4.1.7 on 2023-06-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palpites', '0008_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cor',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
